Table Component PatternFly Migration
distributed-system-analysis/pbench-dashboard pull request #124
Opened 2021-02-04 22:43 UTC by gurbirkalsi

2021-02-05 13:11 UTC, portante reviewed
Great start; @anishaswain, it would be great to work with this with the ToC code, too.

2021-02-12 21:27 UTC, portante reviewed
Is this ready be to tried out with the ToC work from @anishaswain?

2021-02-15 21:27 UTC, gurbirkalsi commented
We need to integrate the `expandable` plugin from `@patternfly/react-table` in order to make table rows expandable for displaying nested children contents. I'll take a look at integrating this with the Table component next.

2021-02-25 05:06 UTC, portante reviewed
Do you have any screen shots on how this might look and behave?

2021-04-08 08:15 UTC, anishaswain approved these changes
The PR looks great @gurbirkalsi . However I do feel that the design is a bit off and needs CSS fixes.

2021-04-08 15:48 UTC, portante approved these changes

2021-04-12 12:17 UTC, aquibbaig requested changes
LGTM @gurbirkalsi! This is great. Just some minor CSS issues which we can fix here. Also, can you please rebase this branch on top of `main` to reference correct config variables?

2021-04-12 12:17 UTC, aquibbaig commented on src/components/Table/index.js
> +    <SearchBar
I personally liked the previous design with the SearchBar being on the same row as "DatePicker". I understand why we moved away from that (as SearchBar is a part of the Table component), I believe at least we should apply a "margin-top" property to separate it from the "DatePicker component up top". 

![React table](https://user-images.githubusercontent.com/26324376/114390285-0eaa2a80-9b64-11eb-850f-520a1af177ca.png)

2021-04-12 12:17 UTC, aquibbaig commented on src/components/Table/index.less
> +}
Adding this property on hover causes the whole table to shift laterally some pixels, I believe changing the row color on focus should be enough visual cue and we can drop this change.

2021-04-12 12:17 UTC, aquibbaig commented on src/components/Table/index.less
> +}
Steps to reproduce this:
In the controllers tab, hover on the name of the controller as it turns bold, sometimes when the name is too large, it causes the table to shift in horizontal direction by some amount of pixels.

Additional information:
I inspected the source maps to find where this css was coming from, to my surprise it was referenced by `index.css` loaded by `localhost:8000/node_modules/jschart`. (no idea why)

2021-04-12 18:09 UTC, gurbirkalsi commented on src/components/Table/index.js
> +    <SearchBar
Thanks for catching this @aquibbaig, it seems we had a typo when passing style props as `styles` whereas we needed `style`.

2021-04-12 18:18 UTC, gurbirkalsi commented on src/components/Table/index.less
> +}
I've updated the Table to now handle hovering using the `"pf-m-hoverable"` class name. This should allow us to maintain the appropriate visual key for hovering and highlighting a controller according to PatternFly best practices.

2021-04-12 18:20 UTC, gurbirkalsi commented
@anishaswain This PR is only using PatternFly CSS dependencies and only injects custom CSS for handling overflows when the number of table rows exceed the page height. Here is the CSS & HTML being referenced from PatternFly's documentation: https://www.patternfly.org/v4/components/table/html#

In the case we need more visual cues or adjustments to design, I'd recommend filing an issue at https://github.com/patternfly/patternfly-design to address white spaces.

2021-04-12 18:22 UTC, gurbirkalsi commented
@aquibbaig Unfortunately, I wasn't able to reproduce the favoriting records issue and results page with the heading `[Object object]`. Were there any logging errors or output that might be helpful in debugging this?

2021-04-20 11:07 UTC, aquibbaig approved these changes
LGTM! @gurbirkalsi

2021-04-20 11:08 UTC, aquibbaig commented
> @aquibbaig Unfortunately, I wasn't able to reproduce the favoriting records issue and results page with the heading `[Object object]`. Were there any logging errors or output that might be helpful in debugging this?

This issue has been resolved now. Just tested it out

2021-04-20 13:36 UTC, merged