Remove unused jspdf dependency from node modules
distributed-system-analysis/pbench-dashboard pull request #135
Opened 2021-03-30 19:04 UTC by gurbirkalsi

This PR addresses the following Dependabot alert: https://github.com/distributed-system-analysis/pbench-dashboard/security/dependabot/package.json/jspdf/open

2021-03-30 19:53 UTC, portante requested changes
Looks good, just needs some passing tests ...

2021-03-31 04:13 UTC, aquibbaig commented
@portante I'm afraid the tests are failing due to mock generation PR. Asserting randomly generated values is a bit tricky. We should probably use a different approach with our e2e tests. (like "table data should not be null", "date picker component months should not be null", etc).

2021-03-31 04:14 UTC, aquibbaig approved these changes
Looks good!

2021-04-06 12:44 UTC, portante approved these changes

2021-04-06 12:44 UTC, merged