reference correct mock env variable in config
distributed-system-analysis/pbench-dashboard pull request #138
Opened 2021-03-31 06:16 UTC by aquibbaig

Fixes #137.

2021-03-31 12:42 UTC, portante requested changes
Looks good, but tests are failing.

2021-03-31 13:28 UTC, aquibbaig commented
> Looks good, but tests are failing.

@portante Will fix that in #136

2021-04-01 18:16 UTC, gurbirkalsi approved these changes

2021-04-01 21:42 UTC, portante approved these changes

2021-04-01 21:42 UTC, merged