Phase out private routes from routing schema
distributed-system-analysis/pbench-dashboard pull request #161
Opened 2021-05-19 17:32 UTC by gurbirkalsi

Pbench dashboard will verify user auth status according to successful or unsuccessful API responses given a valid user token. In cases where the server returns an error, the user will be routed to authentication pages.

2021-05-20 01:46 UTC, portante approved these changes

2021-05-20 01:48 UTC, portante requested changes
Well, it looks good to me, but for some reason the unit tests are not passing.

2021-05-20 18:04 UTC, portante approved these changes

2021-05-31 04:08 UTC, aquibbaig approved these changes

2021-05-31 04:19 UTC, merged