Integrate user authentication via Apollo Server
distributed-system-analysis/pbench-dashboard pull request #70
Opened 2020-07-07 20:19 UTC by gurbirkalsi

Apollo Server is an open-source GraphQL server that will serve as middleware for handling user authentication hooks such as login, register, etc. Apollo takes the Prisma schema context and resolves mutations to data managed by Prisma. 

User authentication involves generating tokens via `jsonwebtoken` and handling encyrption via `bcryptjs` for ensuring integrity of generated tokens.

2020-07-09 18:28 UTC, portante requested changes
Just a simple comment cleanup, but looks good!

2020-07-09 18:28 UTC, portante commented on prisma/README.md
> +│   │   ├── index.js              # Apollo server entrypoint
One level too deep?

2020-07-14 04:54 UTC, gurbirkalsi commented on prisma/README.md
> +│   │   ├── index.js              # Apollo server entrypoint
Fixed!

2020-07-14 07:38 UTC, anishaswain approved these changes
lgtm

2020-07-14 11:50 UTC, portante approved these changes

2020-07-14 20:32 UTC, merged