Dashboard APIs
distributed-system-analysis/pbench-dashboard pull request #75
Opened 2020-07-24 18:21 UTC by FuqingWang

Replaced all ElasticSearch calls to use pbench server APIs
Server address {pbench_server) needs to be specified in datastoreConfig.js

2020-07-27 19:50 UTC, portante approved these changes
Good first start.

Next, we'll want to next remove all the `datastoreConfig` references in the brower code, and pass enough information to the `/download` endpoint for the server to fill in from its local configuration.

We'll also want to consider making more specialized APIs which accept a date range, and let the server side figure out which indices to search.

2020-08-03 05:52 UTC, aquibbaig requested changes
Thanks @FuqingWang for this pull request.  This looks good to me, just minor changes to a variable name

2020-08-03 05:52 UTC, aquibbaig commented on src/services/dashboard.js
> +    const url = `/${getAllMonthsWithinRange(
what if we rename this url to `indices` as a URL will mostly refer to the entire request URL?

2020-08-03 05:52 UTC, aquibbaig commented on src/services/dashboard.js
> +  const url = `/${getAllMonthsWithinRange(
same as above

2020-08-03 05:52 UTC, aquibbaig commented on src/services/dashboard.js
> +  const url = `/${parseMonths(
same as above

2020-08-03 05:55 UTC, aquibbaig commented
@FuqingWang For the e2e tests which are failing for the search page, I will have a look into it today cause it is mostly due to the datepicker work that we had done last time which essentially changed a lot of components on the dashboard.

2020-08-03 14:13 UTC, gurbirkalsi commented
I've merged PR #76 - let's rebase this PR on master and re-run the Travis CI build.

2020-08-24 08:27 UTC, aquibbaig commented
@gurbirkalsi Looks like `mockMappings` are not getting imported to the Search page for some reason.

2020-08-31 05:16 UTC, aquibbaig requested changes
@FuqingWang Ran a debug at your work. I'm pretty sure why it fails now. Please take a look at the comments and let me know what you think

2020-08-31 05:16 UTC, aquibbaig commented on src/services/datastore.js
> +  const endpoint = `${datastoreConfig.pbench_server}/elasticsearch`;
Is there a specific entry in `datastoreConfig` for `pbench_server`? If not, this field will always be undefined. This URL gets you the indices without which the search header won't finish loading, if it won't finish loading, then none of the tests in the Search page will work. That explains why your tests are failing. You might wanna take a look at this endpoint here

2020-08-31 05:16 UTC, aquibbaig commented on src/services/explore.js
> +  const endpoint = `${datastoreConfig.pbench_server}/graphql`;
Similar to the above comment. Please mention in the PR if we have to add new fields to our `datastoreConfig`

2020-10-23 23:53 UTC, npalaska commented
@aquibbaig you are right we need pbench_server in datastoreConfig and then we can safely remove the references to es and graphql from datastoreConfig file. This PR needs a little more cleanup I am opening a new PR to work to ramp up but will keep fuqing's commit.

2020-10-24 03:57 UTC, npalaska reviewed
Further work is tracked in PR https://github.com/distributed-system-analysis/pbench-dashboard/pull/95

2020-10-26 11:34 UTC, dbutenhof reviewed
As Aquib says, we really need to change `config.json.j2` (and whatever drives the template resolution) to include the pbench server endpoint as well as removing the direct elasticsearch and graphql endpoints.

2020-10-26 13:07 UTC, portante commented
Closing in favor of #95.

2020-10-26 13:07 UTC, closed without merging