Bug fixes in User Authentication Work
distributed-system-analysis/pbench-dashboard pull request #84
Opened 2020-08-24 08:53 UTC by Anisha1234

Fixes #81 
Fixes `warning: <avatarIcon /> is using incorrect casing.`

2020-08-24 08:54 UTC, Anisha1234 commented
@aquibbaig let me know if the PR resolves the issues in #81

2020-08-24 09:12 UTC, aquibbaig approved these changes
LGTM :rocket:

2020-08-24 14:25 UTC, gurbirkalsi requested changes
Great work @Anisha1234, just one small fix before we merge!

2020-08-24 14:25 UTC, gurbirkalsi commented on src/components/GlobalHeader/index.js
> +    const { dispatch, auth } = this.props;
The `auth` namespace is declared but its value is never read. Can we consider removing this reference?

2020-08-26 14:18 UTC, gurbirkalsi approved these changes

2020-08-26 14:18 UTC, merged